### ISSUE TITLE
Missing utcParse parse function

### ISSUE THREAD

**Issue by domoritz** [vega/vega-util#5]
We have a `timeParse` function but no `utcParse` method.

**Comment by jheer** [comment]
I'm not sure how this would/should work. By default, `toDate` falls back on `Date.parse` which defaults to different time zones based on the input string. For example, absolute time can be specified with ISO standard datetime strings.

For more control, we support a [`utcParse` expression method](https://github.com/vega/vega-parser/blob/master/src/parsers/expression/format.js) (the analog to `timeParse`) that takes a specific formatting string. In any case, for custom formatting strings use `timeParse` and `utcParse`!
